DROP TABLE Employee_Jobs CASCADE;
DROP TABLE Departments CASCADE;
DROP TABLE Locations CASCADE;
DROP TABLE Addresses CASCADE;
DROP TABLE Phone_Numbers CASCADE;
DROP TABLE Employees CASCADE;
DROP TABLE Jobs CASCADE;
DROP TABLE Employee_Performance;
DROP TABLE Employee_Termination;
DROP TABLE Address_Types;
DROP TABLE Phone_Types;
DROP TABLE Countries;
DROP TABLE Provinces;
DROP TABLE Cities;
DROP TABLE Employee_Addresses;
DROP TABLE Employee_Departments;
DROP TABLE Employee_Locations;
DROP TABLE Managers;
DROP TABLE load_department;
DROP TABLE load_employees;
DROP TABLE load_job;
DROP TABLE load_location;
