/* Matthew Mulenga */
/* mam558 */
/* 11144528 */

CREATE TABLE employees_audit (
  id SERIAL,
  employee_number VARCHAR(200),
  title VARCHAR(20),
  first_name VARCHAR(100),
  middle_name VARCHAR(100),
  last_name VARCHAR(100),
  gender GENDER,
  ssn ssnType,
  birth_date DATE,
  hire_date DATE,
  rehire_date DATE,
  termination_date DATE,
  marital_status_id INT,
  home_email VARCHAR(200),
  employment_status_id INT,
  term_type_id INT,
  term_reason_id INT,
  audit_date TIMESTAMP,
  audit_action VARCHAR(10),
  audit_user VARCHAR(50),
  PRIMARY KEY(id)
);

CREATE TABLE employee_jobs_audit (
  id SERIAL,
  employee_id INT,
  job_id INT,
  effective_date DATE,
  expiry_date DATE,
  pay_amount INT,
  standard_hours INT,
  employee_type_id INT,
  employee_status_id INT,
  audit_date TIMESTAMP,
  audit_action VARCHAR(10),
  audit_user VARCHAR(50),
  PRIMARY KEY (id)
);

CREATE TABLE employee_history (
  id SERIAL,
  employee_number VARCHAR(200),
  employee_id INT,
  title VARCHAR(20),
  first_name VARCHAR(100),
  middle_name VARCHAR(100),
  last_name VARCHAR(100),
  gender GENDER,
  ssn ssnType,
  birth_date DATE,
  marital_status_code VARCHAR(10),
  marital_status_name VARCHAR(100),
  employee_status_code VARCHAR(10),
  employee_status_name VARCHAR(100),
  orig_hire_date DATE,
  rehire_date DATE,
  termination_date DATE,
  termination_reason_code VARCHAR(10),
  termination_reason_name VARCHAR(100),
  termination_type_code VARCHAR(10),
  termination_type_name VARCHAR(100),
  job_code VARCHAR(10),
  job_title VARCHAR(100),
  job_st_date DATE,
  job_end_date DATE,
  pay_amount INT,
  standard_hours INT,
  employee_type_code VARCHAR(10),
  employee_type_name VARCHAR(100),
  employment_status_code VARCHAR(10),
  employment_status_name VARCHAR(100),
  department_code VARCHAR(10),
  department_name VARCHAR(100),
  location_code VARCHAR(10),
  location_name VARCHAR(100),
  pay_frequency_code VARCHAR(10),
  pay_frequency_name VARCHAR(100),
  pay_type_code VARCHAR(10),
  pay_type_name VARCHAR(100),
  supervisor_job_code VARCHAR(10),
  supervisor_job_title VARCHAR(100),
  history_timestamp TIMESTAMP,
  PRIMARY KEY(id)
);
